"""
Datacenter placement analysis for the IEEE 14-bus use case.

Sweeps all 14 buses as potential datacenter locations (flat 200 MW, 24 h),
runs Economic Dispatch for each, ranks feasible placements by total cost,
and writes assets_dc_bus{N}.py for every feasible bus.

Run from the quantum-storage-siting root:
    python use_cases/ieee14/site_datacenter.py

Or directly:
    cd use_cases/ieee14 && python site_datacenter.py
"""

import importlib.util
import os
import sys


# ---------------------------------------------------------------------------
# Path setup
# ---------------------------------------------------------------------------
_here = os.path.dirname(os.path.abspath(__file__))
_pjm5_root = os.path.abspath(os.path.join(_here, "..", ".."))
_tutorial = os.path.abspath(
    os.path.join(_pjm5_root, "..", "..", "..", "Tutorial", "Quantum Network Flow Diagrams")
)

for p in [_tutorial, _pjm5_root, _here]:
    if p not in sys.path:
        sys.path.insert(0, p)

# ---------------------------------------------------------------------------
# Load grid, assets, locations
# ---------------------------------------------------------------------------
_grid_spec = importlib.util.spec_from_file_location("ieee14", os.path.join(_here, "ieee14.py"))
assert _grid_spec is not None and _grid_spec.loader is not None
_grid_mod = importlib.util.module_from_spec(_grid_spec)
_grid_spec.loader.exec_module(_grid_mod)  # type: ignore[union-attr]

from assets import GENERATORS, BATTERIES  # noqa: E402
from locations import GENERATOR_LOCATIONS, BATTERY_LOCATIONS  # noqa: E402
from solvers.ed import run_ed  # noqa: E402

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
DC_MW = 200      # datacenter load (MW), flat 24 h
T = 24           # simulation horizon (hours)
N_BUSES = 14

# ---------------------------------------------------------------------------
# Sweep
# ---------------------------------------------------------------------------
print("Datacenter placement analysis — IEEE 14-bus")
print(f"DC load: {DC_MW} MW flat, T={T} h")
print(f"Sweeping all {N_BUSES} buses...\n")

feasible: list[tuple[int, float]] = []
infeasible: list[int] = []

for bus in range(1, N_BUSES + 1):
    grid = _grid_mod.Case()
    # Inject flat DC load at this bus (0-indexed row = bus - 1)
    grid.power_demand[bus - 1, :] += DC_MW

    try:
        result = run_ed(grid, GENERATORS, BATTERIES, GENERATOR_LOCATIONS, BATTERY_LOCATIONS, T)
        cost = result.total_cost
        feasible.append((bus, cost))
        print(f"  Bus {bus:>2}: ${cost:>14,.0f}")
    except Exception as exc:
        infeasible.append(bus)
        print(f"  Bus {bus:>2}: INFEASIBLE  ({type(exc).__name__})")

# ---------------------------------------------------------------------------
# Rank and print
# ---------------------------------------------------------------------------
feasible.sort(key=lambda x: x[1])

print()
if feasible:
    print(f"{'Rank':<6} {'Bus':>4}  {'Total Cost ($)':>16}  {'Delta vs Best':>16}")
    print("-" * 48)
    best_cost = feasible[0][1]
    for rank, (bus, cost) in enumerate(feasible, start=1):
        delta = cost - best_cost
        delta_str = f"+${delta:,.0f}" if delta > 0 else "-"
        print(f"{rank:<6} {bus:>4}  {cost:>16,.0f}  {delta_str:>16}")
    print()

# ---------------------------------------------------------------------------
# Write assets_dc_bus{N}.py for each feasible bus
# ---------------------------------------------------------------------------
if feasible:
    # Remove any stale assets_dc_bus{N}.py files from previous runs before writing new ones
    import glob as _glob
    for _stale in _glob.glob(os.path.join(_here, "assets_dc_bus*.py")):
        os.remove(_stale)

    print("Writing assets files for feasible buses...")
    best_bus = feasible[0][0]
    for rank, (bus, cost) in enumerate(feasible, start=1):
        fname = os.path.join(_here, f"assets_dc_bus{bus}.py")
        lines = [
            f"# Datacenter at bus {bus} — {DC_MW} MW flat, 24 h",
            "# Generated by site_datacenter.py",
            f"# Rank {rank} of {len(feasible)} feasible buses  |  total cost ${cost:,.0f}",
            "# Do not edit manually — re-run site_datacenter.py to regenerate",
            "",
            "from assets import GENERATORS, BATTERIES  # noqa: F401",
            "",
            f"DATACENTER_BUS: int = {bus}",
            f"DATACENTER_MW: float = {DC_MW}.0",
        ]
        with open(fname, "w") as fh:
            fh.write("\n".join(lines) + "\n")
        tag = " ← best" if bus == best_bus else ""
        print(f"  assets_dc_bus{bus}.py  (rank {rank}){tag}")

    print()
    print(f"Best datacenter location: Bus {best_bus}  (${feasible[0][1]:,.0f})")
    print("\nTo run battery siting with this datacenter:")
    print(f"  python main.py  → select ieee14 → select assets_dc_bus{best_bus}.py")

if infeasible:
    print(f"\nInfeasible buses (line limits exceeded): {infeasible}")
