# Datacenter at bus 5 — 200 MW flat, 24 h
# Generated by site_datacenter.py
# Rank 4 of 4 feasible buses  |  total cost $234,906
# Do not edit manually — re-run site_datacenter.py to regenerate

from assets import GENERATORS, BATTERIES  # noqa: F401

DATACENTER_BUS: int = 5
DATACENTER_MW: float = 200.0
