# Datacenter at bus 1 — 200 MW flat, 24 h
# Generated by site_datacenter.py
# Rank 1 of 4 feasible buses  |  total cost $228,429
# Do not edit manually — re-run site_datacenter.py to regenerate

from assets import GENERATORS, BATTERIES  # noqa: F401

DATACENTER_BUS: int = 1
DATACENTER_MW: float = 200.0
